name: 'oneonone'
version: '1.0.0'
profile: 'transform'
require-dbt-version: [">=1.9.0", "<2.0.0"]

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  oneonone:
    staging:
      +materialized: view
      +schema: staging
      +tags: ['staging']
    intermediate:
      +materialized: view
      +schema: intermediate
      +tags: ['intermediate']
    marts:
      +materialized: table
      +schema: marts
      +tags: ['marts']
    metrics:
      +tags: ['metrics']

seeds:
  oneonone:
    +schema: staging
    plan_pricing:
      +column_types:
        plan: varchar
        monthly_price: number(18,2)
        annual_price: number(18,2)